# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  zookeeper:
    image: ghcr.io/bitmoa/zookeeper:3.9
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitmoa/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  zookeeper_data:
    driver: local
