# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  neo4j:
    image: ghcr.io/bitmoa/neo4j:5
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/bitmoa'
volumes:
  neo4j_data:
    driver: local
