# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:

  envoy:
    image: ghcr.io/bitmoa/envoy:1.35
    volumes:
      - ./examples/frontend.yaml:/opt/bitmoa/envoy/conf/envoy.yaml

  service1:
    image: bitmoa/nginx

  service2:
    image: bitmoa/apache

