# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  golang:
    tty: true # Enables debugging capabilities when attached to this container.
    image: ghcr.io/bitmoa/golang:1.25
    command: ["sleep", "infinity"] # To keep the container running
