# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  influxdb:
    image: ghcr.io/bitmoa/influxdb:3
    ports:
      - 8181:8181
    environment:
      - INFLUXDB_NODE_ID=0
    volumes:
      - influxdb_data:/bitmoa/influxdb
volumes:
  influxdb_data:
    driver: local
