# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  postgresql:
    image: ghcr.io/bitmoa/postgresql:latest
    ports:
      - '5432'
    volumes:
      - 'postgresql_data:/bitmoa/postgresql'
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitmoa
      - POSTGRESQL_DATABASE=kong
      - ALLOW_EMPTY_PASSWORD=yes
  kong:
    image: ghcr.io/bitmoa/kong:3
    ports:
      - 18000:8000
      - 18443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgresql
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=bitmoa
      # See NGINX worker_processes setting at http://nginx.org/en/docs/ngx_core_module.html#worker_processes
      # If in doubt, set to the amount of CPU cores divided by the number of Kong/PostgreSQL nodes in the machine
      - KONG_NGINX_WORKER_PROCESSES=2
  kong2:
    image: ghcr.io/bitmoa/kong:3
    ports:
      - 28000:8000
      - 28443:8443
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgresql
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=bitmoa
      # See NGINX worker_processes setting at http://nginx.org/en/docs/ngx_core_module.html#worker_processes
      # If in doubt, set to the amount of CPU cores divided by the number of Kong/PostgreSQL nodes in the machine
      - KONG_NGINX_WORKER_PROCESSES=2
volumes:
  postgresql_data:
    driver: local
