# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mysql:
    image: ghcr.io/bitmoa/mysql:latest
    volumes:
      - 'mysql_data:/bitmoa/mysql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_ghost
      - MYSQL_DATABASE=bitmoa_ghost
  ghost:
    image: ghcr.io/bitmoa/ghost:6
    ports:
      - '80:2368'
    volumes:
      - 'ghost_data:/bitmoa/ghost'
    depends_on:
      - mysql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_DATABASE_HOST=mysql
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitmoa_ghost
volumes:
  mysql_data:
    driver: local
  ghost_data:
    driver: local
