# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  tomcat:
    image: ghcr.io/bitmoa/tomcat:11.0
    ports:
      - '8080:8080'
    volumes:
      - 'tomcat_data:/bitmoa/tomcat'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  tomcat_data:
    driver: local
