# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  telegraf:
    image: ghcr.io/bitmoa/telegraf:1
    volumes:
      - ./telegraf.conf:/opt/bitmoa/telegraf/config/telegraf.conf:ro
    command:
      - --config
      - /opt/bitmoa/telegraf/config/telegraf.conf
    ports:
      - '8080:8080'
