# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  solr:
    image: ghcr.io/bitmoa/solr:9
    environment:
      - SOLR_ENABLE_AUTHENTICATION=yes
    ports:
      - '8983:8983'
    volumes:
      - 'solr_data:/bitmoa/solr'
volumes:
  solr_data:
    driver: local
