# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  jenkins:
    image: ghcr.io/bitmoa/jenkins:2
    ports:
      - '80:8080'
    environment:
      - JENKINS_PASSWORD=bitmoa
    volumes:
      - 'jenkins_data:/bitmoa/jenkins'

volumes:
  jenkins_data:
    driver: local
