# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  postgresql:
    image: ghcr.io/bitmoa/postgresql:latest
    volumes:
      - 'postgresql_data:/bitmoa/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitmoa_mastodon
      - POSTGRESQL_USERNAME=bn_mastodon
      - POSTGRESQL_PASSWORD=bitmoa1
  redis:
    image: ghcr.io/bitmoa/redis:latest
    volumes:
      - 'redis_data:/bitmoa/redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  elasticsearch:
    image: ghcr.io/bitmoa/elasticsearch:latest
    volumes:
      - 'elasticsearch_data:/bitmoa/elasticsearch/data'
    environment:
      - ELASTICSEARCH_ENABLE_SECURITY=true
      - ELASTICSEARCH_SKIP_TRANSPORT_TLS=true
      - ELASTICSEARCH_ENABLE_REST_TLS=false
      - ELASTICSEARCH_PASSWORD=bitmoa123
  mastodon:
    image: ghcr.io/bitmoa/mastodon:4
    ports:
      - 80:3000
    volumes:
      - 'mastodon_data:/bitmoa/mastodon'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MASTODON_MODE=web
      - MASTODON_DATABASE_PASSWORD=bitmoa1
      - MASTODON_ELASTICSEARCH_PASSWORD=bitmoa123
  mastodon-streaming:
    image: ghcr.io/bitmoa/mastodon:4
    ports:
      - 4000:4000
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MASTODON_MODE=streaming
      - MASTODON_DATABASE_PASSWORD=bitmoa1
      - MASTODON_ELASTICSEARCH_PASSWORD=bitmoa123
  mastodon-sidekiq:
    image: ghcr.io/bitmoa/mastodon:4
    volumes:
      - 'mastodon_data:/bitmoa/mastodon'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MASTODON_MODE=sidekiq
      - MASTODON_DATABASE_PASSWORD=bitmoa1
      - MASTODON_ELASTICSEARCH_PASSWORD=bitmoa123
volumes:
  postgresql_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  mastodon_data:
    driver: local
