# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  minio:
    image: ghcr.io/bitmoa/minio:2025
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitmoa/minio/data'

volumes:
  minio_data:
    driver: local
