# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  postgresql:
    image: ghcr.io/bitmoa/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitmoa/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local
