name: CD

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write # ghcr
  id-token: write # cosign

env:
  DOCKER_REGISTRY: ghcr.io
  ORG: bitmoa

jobs:
  build-and-sign:
    runs-on: ubuntu-22.04
    name: Build and push container on tag
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.2
      - name: Cosign Version
        run: cosign version

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse tag and locate Dockerfile (regex + version-prefix candidates)
        id: parse
        run: |
          bash ./.github/parse-tag.sh

      - name: Build and push multi-arch image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ steps.parse.outputs.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.parse.outputs.image_tag }}

      - name: cosign
        env:
          IMAGE_TAG: ${{ steps.parse.outputs.image_tag }}
        run: |
          set -euo pipefail
          IMAGE_DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' "${IMAGE_TAG}" | cut -d'@' -f2)"
          cosign sign --yes "${IMAGE_TAG}@${IMAGE_DIGEST}"
